name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  version:
    name: Increment version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: ğŸ·ï¸ Push next SemVer tag
        id: semver-tag
        uses: K-Phoen/semver-release-action@v1.3.2
        with:
          release_branch: master
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
    outputs:
      tag: ${{ steps.semver-tag.outputs.tag }}
  release:
    name: Publish GitHub release
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”½ Checkout repository
        uses: actions/checkout@v4
      - name: ğŸ“ Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: false
          git-push: false
          skip-on-empty: false
          skip-version-file: true
          skip-tag: true
          skip-commit: true
      - name: ğŸ Publish GitHub release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ needs.version.outputs.tag }}
          release_name: ${{ needs.version.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
  deliver:
    name: Deliver
    needs: version
    uses: ./.github/workflows/delivery.yml
    with:
      version: ${{ needs.version.outputs.tag  }}
    secrets: inherit
  notify:
    name: Notify
    needs: [ version, deliver ]
    uses: ./.github/workflows/notification.yml
    with:
      version: ${{ needs.version.outputs.tag  }}
    secrets: inherit
  deploy:
    name: Deploy
    needs: deliver
    uses: ./.github/workflows/deployment.yml
    secrets: inherit