name: Report

on:
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: Publish test report
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: 'tests/**/*.trx'
      - name: ğŸ“Š Generate report
        uses: dorny/test-reporter@v1
        with:
          name: .NET test results
          artifact: test-results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx
