name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ '*' ]

jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”½ Checkout repository
        uses: actions/checkout@v3
      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore
      - name: âš’ Build solution
        run: dotnet build --no-restore
      - name: ğŸª² Run tests
        run: dotnet test --no-build --verbosity normal --logger trx
      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: 'tests/**/*.trx'
  publish-test-report:
    name: Report
    uses: ./.github/workflows/report.yml
    secrets: inherit